### ISSUE TITLE
Screener returns an empty array

### ISSUE THREAD

**Issue by meerkat-citronella** [nielse63/stonksjs#57]
**Describe the bug** A clear and concise description of what the bug is.

Please forgive me if I am missing something obvious, I am relatively new to programming.

Passing the example screen (https://finviz.com/screener.ashx?v=111&s=ta_topgainers) to `finviz.screen()` returns a promise that resolves to an empty array. 

**To Reproduce** Steps to reproduce the behavior:

My code: 

```
const finviz = require("@stonksjs/finviz");

const getTopGainers = async () => {
  const symbols = await finviz.screener(
    "https://finviz.com/screener.ashx?v=111&s=ta_topgainers"
  );
  console.log(symbols);
};

getTopGainers();

// => []
```

My package.json:

```
{
  "name": "alpaca-trades",
  "version": "1.0.0",
  "description": "backend for sending requests to alpaca",
  "main": "index.js",
  "dependencies": {
    "@stonksjs/finviz": "^1.0.1",
    "node-fetch": "^2.6.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

**Expected behavior** A clear and concise description of what you expected to happen.

Expect it to return an array of symbol in the response schema as described on npm

**Environment** A concise description of your environment: GatorGrader version, python version,
operating system, etc.

node v15.0.1
npm  v6.14.11
macOS 10.15.7

**Additional context** Add any other context about the problem here.

**Comment by nielse63** [comment]
@meerkat-citronella Sorry for the late reply. I'll take a look at the issue and get back to you shortly.

**Comment by meerkat-citronella** [comment]
Np. I went ahead and made my own package for just this functionality: 

https://www.npmjs.com/package/node-finviz-screener
